apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "control-api.fullname" . }}-config
  labels:
    {{- include "control-api.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.api.env.port | quote }}
  READ_TIMEOUT: {{ .Values.api.env.readTimeout | quote }}
  WRITE_TIMEOUT: {{ .Values.api.env.writeTimeout | quote }}
  IDLE_TIMEOUT: {{ .Values.api.env.idleTimeout | quote }}
  JWT_EXPIRY: {{ .Values.api.env.jwtExpiry | quote }}
