apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "control-api.fullname" . }}-data-tier
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "control-api.labels" . | nindent 14 }}
