apiVersion: v1
kind: Service
metadata:
  name: {{ include "control-api.fullname" . }}
  labels: {{- include "control-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector: {{- include "control-api.labels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: {{ .Values.api.port }}
